{% set name = "kubeflow-katib" %}
{% set version = "0.17.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/kubeflow-katib-{{ version }}.tar.gz
  sha256: f8c962757d25cb2062936cc90cc969ab2a302effd5b837e7c393495e5edd41a7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - certifi >=14.05.14
    - six >=1.10
    - setuptools >=21.0.0
    - urllib3 >=1.15.1
    - python-kubernetes >=23.6.0
    - grpcio >=1.41.1
    - protobuf <5,>=4.21.12

test:
  imports:
    - kubeflow.katib
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/kubeflow/katib/tree/master/sdk/python
  summary: Katib Python SDK
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - andreyvelich
    - tenzen-y
    - droctothorpe
    - iamthebot
