{% set name = "kubeflow-katib" %}
{% set version = "0.16.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/kubeflow-katib-{{ version }}.tar.gz
  sha256: fd487ecfb4b7afe90fcde954356eb0eb6da8c4ccb817fe10caba9a12d0dedc67

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - certifi >=14.05.14
    - six >=1.10
    - setuptools >=21.0.0
    - urllib3 >=1.15.1
    - python-kubernetes >=23.6.0
    - grpcio >=1.41.1
    - protobuf >=3.19.5,<=3.20.3

test:
  imports:
    - kubeflow.katib
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/kubeflow/katib/tree/master/sdk/python
  summary: Katib Python SDK
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - andreyvelich
    - tenzen-y
    - droctothorpe
    - iamthebot
